steps:
  - name: 'node:18-alpine'
    entrypoint: 'npm'
    args: ['install']
  - name: 'node:18-alpine'
    entrypoint: 'npm'
    args: ['run', 'build', '--', 'authentication']
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-southeast1-docker.pkg.dev/crashboy-395715/crashboy/authentication:latest',
        '-f',
        './Dockerfile.authentication',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-southeast1-docker.pkg.dev/crashboy-395715/crashboy/authentication:latest',
      ]
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   entrypoint: gcloud
  #   args:
  #     [
  #       'run',
  #       'deploy',
  #       'authentication',
  #       '--image',
  #       'asia-southeast1-docker.pkg.dev/crashboy-395715/crashboy/authentication:latest',
  #       '--platform=managed',
  #       '--region=asia-southeast1',
  #       '--allow-unauthenticated',
  #     ]
# logsBucket: 'gs://buildlogging'
# options:
#   logging: GCS_ONLY
